### ISSUE TITLE
Blue border on links

### ISSUE THREAD

**Issue by codazoda** [codazoda/neatcss#48]
When I click on a link a blue border is drawn around that link. I believe this is default browser behavior but I think I'd like to remove that border. Most of the time you don't notice this because it goes so quickly. I noticed it on [notes.joeldare.com](https://notes.joeldare.com) when I added a link to a form with a target of `_blank`.

**Comment by codazoda** [comment]
I fixed this in the upcoming version.

**Comment by codazoda** [comment]
Looks like my `fix` didn't work. I need to take a second look at this.

**Comment by DeJayDev** [comment]
I can reproduce this issue with Firefox 128 using Arch Linux but removing the following snippet appears to solve it 🤔

```css
*:focus {
  outline: var(--light);
  box-shadow: 0 0 0 .25em var(--link);
}
```
